#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bridge.fullname" . }}
  labels:
    app: {{ template "bridge.name" . }}
    chart: {{ template "bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.bridgeNode.deploymentAnnotations }}
  annotations:
    {{- toYaml .Values.bridgeNode.deploymentAnnotations | nindent 4 }}
{{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.bridgeNode.replicaCount }}
  {{- if .Values.bridgeNode.strategy }}
  strategy:
    {{- toYaml .Values.bridgeNode.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "bridge.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        # Force reload on config changes
        checksum/bridge_config.py: {{ include "bridge-config" . | sha256sum }}
        checksum/bridge_init.sh: {{ tpl .Values.init.initscript . | sha256sum }}
        checksum/bridge_bootstrap.sh: {{ tpl .Values.bootstrapScript . | sha256sum }}
        checksum/connections: {{ .Values.bridgeNode.connections | toYaml | sha256sum }}
        checksum/extraConfigs: {{ .Values.extraConfigs | toYaml | sha256sum }}
        checksum/extraSecrets: {{ .Values.extraSecrets | toYaml | sha256sum }}
        checksum/extraSecretEnv: {{ .Values.extraSecretEnv | toYaml | sha256sum }}
        checksum/configOverrides: {{ .Values.configOverrides | toYaml | sha256sum }}
        checksum/configOverridesFiles: {{ .Values.configOverridesFiles | toYaml | sha256sum }}
        {{- if .Values.bridgeNode.forceReload }}
        # Optionally force the thing to reload
        force-reload: {{ randAlphaNum 5 | quote }}
        {{- end }}
      {{- if .Values.bridgeNode.podAnnotations }}
        {{- toYaml .Values.bridgeNode.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "bridge.name" . }}
        release: {{ .Release.Name }}
      {{- if .Values.bridgeNode.podLabels }}
        {{- toYaml .Values.bridgeNode.podLabels | nindent 8 }}
      {{- end }}
    spec:
      {{- if or (.Values.serviceAccount.create) (.Values.serviceAccountName) }}
      serviceAccountName: {{ template "bridge.serviceAccountName" . }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.runAsUser }}
      {{- if .Values.bridgeNode.podSecurityContext }}
        {{- toYaml .Values.bridgeNode.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.bridgeNode.initContainers }}
      initContainers:
      {{-  tpl (toYaml .Values.bridgeNode.initContainers) . | nindent 6 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases: {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.bridgeNode.containerSecurityContext }}
          securityContext: {{- toYaml .Values.bridgeNode.containerSecurityContext | nindent 12 }}
          {{- end }}
          command: {{  tpl (toJson .Values.bridgeNode.command) . }}
          env:
            - name: "BRIDGE_PORT"
              value: {{ .Values.service.port | quote}}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key | quote}}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.bridgeNode.env }}
            - name: {{ $key | quote}}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.extraEnvRaw }}
            {{- toYaml .Values.extraEnvRaw | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ tpl .Values.envFromSecret . | quote }}
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ tpl . $ | quote }}
            {{- end }}
          volumeMounts:
            - name: bridge-config
              mountPath: {{ .Values.configMountPath | quote }}
              readOnly: true
          {{- if .Values.extraConfigs }}
            - name: bridge-extra-config
              mountPath: {{ .Values.extraConfigMountPath | quote }}
              readOnly: true
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          {{- tpl (toYaml .) $ | nindent 12 -}}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.bridgeNode.startupProbe }}
          startupProbe:
            {{- .Values.bridgeNode.startupProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.bridgeNode.readinessProbe }}
          readinessProbe:
            {{- .Values.bridgeNode.readinessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.bridgeNode.livenessProbe }}
          livenessProbe:
            {{- .Values.bridgeNode.livenessProbe | toYaml | nindent 12 }}
          {{- end }}
          resources:
          {{- if .Values.bridgeNode.resources }}
            {{- toYaml .Values.bridgeNode.resources | nindent 12 }}
          {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}

      volumes:
        - name: bridge-config
          secret:
            secretName: {{ tpl .Values.configFromSecret . }}
        {{- if .Values.extraConfigs }}
        - name: bridge-extra-config
          configMap:
            name: {{ template "bridge.fullname" . }}-extra-config
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- tpl (toYaml .) $ | nindent 8 -}}
        {{- end }}
