#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bridge.fullname" . }}
  labels:
    app: {{ template "bridge.name" . }}
    chart: {{ template "bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "bridge.name" . }}
    release: {{ .Release.Name }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
---
{{- if .Values.bridgeCeleryFlower.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bridge.fullname" . }}-flower"
  labels:
    app: {{ template "bridge.name" . }}
    chart: {{ template "bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.bridgeCeleryFlower.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.bridgeCeleryFlower.service.type }}
  ports:
    - port: {{ .Values.bridgeCeleryFlower.service.port }}
      targetPort: flower
      protocol: TCP
      name: flower
  selector:
    app: {{ template "bridge.name" . }}-flower
    release: {{ .Release.Name }}
  {{- if .Values.bridgeCeleryFlower.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.bridgeCeleryFlower.service.loadBalancerIP }}
  {{- end }}
{{- end }}
---
{{- if .Values.bridgeWebsockets.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bridge.fullname" . }}-ws"
  labels:
    app: {{ template "bridge.name" . }}
    chart: {{ template "bridge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.bridgeWebsockets.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.bridgeWebsockets.service.type }}
  ports:
    - port: {{ .Values.bridgeWebsockets.service.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    app: "{{ template "bridge.name" . }}-ws"
    release: {{ .Release.Name }}
  {{- if .Values.bridgeWebsockets.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.bridgeWebsockets.service.loadBalancerIP }}
  {{- end }}
{{- end }}
